            @php($pct = fn ($value) => number_format((float) $value, 3, ',', '.').'%')
            <h3 style="margin:0 0 4px">Skor Kesehatan Toko Gabungan</h3>
            <p class="muted" style="margin:0 0 12px">Skor 0-100 dari 30 hari terakhir: <code>100 &minus; min(40, %gagal) &minus; min(30, %backlog checklist) &minus; min(30, jumlah tiket terbuka &times; 5)</code>. Diurutkan dari skor terendah &mdash; paling butuh perhatian di atas.</p>
            <div class="table-wrap"><table class="table qris-table"><thead><tr><th>Toko</th><th>Skor</th><th>% Gagal</th><th>Backlog Checklist</th><th>Tiket Terbuka</th></tr></thead><tbody>@forelse($analyticsHealthScore['rows'] as $row)<tr><td>{{ $row['merchant_name'] }}</td><td><span class="badge {{ $row['score'] >= 70 ? 'ok' : ($row['score'] >= 40 ? 'warn' : 'danger') }}">{{ $row['score'] }}</span></td><td>{{ $pct($row['failedRate']) }}</td><td>{{ $row['backlogCount'] }}</td><td>{{ $row['openTickets'] }}</td></tr>@empty<tr><td colspan="5" class="empty"><strong>Belum ada data.</strong>Toko belum punya transaksi 30 hari terakhir.</td></tr>@endforelse</tbody></table></div>

            <h3 style="margin:28px 0 4px">Detail Operasional</h3>
            <div class="grid qris-metrics section">
                <div class="card pad qris-metric danger"><span>Total Transaksi Gagal</span><strong>{{ number_format($analyticsOperations['totalFailed'], 0, ',', '.') }}</strong><small>{{ $periodLabel }}</small></div>
                <div class="card pad qris-metric warn"><span>Ada Tiket Issue Bank/Switching</span><strong>{{ number_format($analyticsOperations['totalWithTicket'], 0, ',', '.') }}</strong><small>Bukti korelasi ke bank</small></div>
            </div>
            <div class="table-wrap"><table class="table qris-table"><thead><tr><th>Toko</th><th>Transaksi Gagal</th><th>Dengan Tiket Bank/Switching</th><th>% Ada Bukti</th></tr></thead><tbody>@forelse($analyticsOperations['perMerchant'] as $row)<tr><td>{{ $row['merchant_name'] }}</td><td>{{ number_format($row['failed_count'], 0, ',', '.') }}</td><td>{{ number_format($row['with_ticket_count'], 0, ',', '.') }}</td><td>{{ $row['failed_count'] > 0 ? $pct(round(($row['with_ticket_count'] / $row['failed_count']) * 100, 2)) : '-' }}</td></tr>@empty<tr><td colspan="4" class="empty"><strong>Belum ada transaksi gagal.</strong>Filter periode ini belum memiliki transaksi gagal/expired/rejected.</td></tr>@endforelse</tbody></table></div>

            <h3 style="margin:28px 0 4px">Deteksi Outlier per Toko</h3>
            <p class="muted" style="margin:0 0 12px">Transaksi hari ini dibanding rata-rata 7 hari terakhir (tidak terpengaruh filter periode di atas). Toko dengan &plusmn;50% dari rata-rata ditandai outlier.</p>
            <div class="table-wrap"><table class="table qris-table"><thead><tr><th>Toko</th><th>Trx Hari Ini</th><th>Rata-rata 7 Hari</th><th>Deviasi</th></tr></thead><tbody>@forelse($analyticsOutlierDetection['rows'] as $row)<tr><td>{{ $row['merchant_name'] }}</td><td>{{ $row['today_trx'] }}</td><td>{{ $row['avg_trx'] }}</td><td>@if($row['deviation_percent'] === null)<span class="muted">-</span>@else<span class="badge {{ $row['is_outlier'] ? 'danger' : 'ok' }}">{{ $row['deviation_percent'] >= 0 ? '+' : '' }}{{ $pct($row['deviation_percent']) }}</span>@endif</td></tr>@empty<tr><td colspan="4" class="empty"><strong>Belum ada data pembanding.</strong>Toko belum punya riwayat 7 hari terakhir.</td></tr>@endforelse</tbody></table></div>

            <h3 style="margin:28px 0 4px">SLA Resolusi Tiket CS</h3>
            <div class="grid qris-metrics section">
                <div class="card pad qris-metric success"><span>Dalam SLA (24 jam)</span><strong>{{ $pct($analyticsTicketSla['withinSlaPercent']) }}</strong><small>{{ $analyticsTicketSla['withinSlaCount'] }} dari {{ $analyticsTicketSla['totalResolved'] }} tiket selesai</small></div>
                <div class="card pad qris-metric primary"><span>Rata-rata Waktu Resolusi</span><strong>{{ number_format($analyticsTicketSla['avgResolutionHours'], 1) }} jam</strong><small>Dari tiket dibuat sampai ditutup</small></div>
            </div>
            <div class="table-wrap"><table class="table qris-table"><thead><tr><th>CS</th><th>Tiket Selesai</th><th>Rata-rata Waktu</th><th>% Dalam SLA</th></tr></thead><tbody>@forelse($analyticsTicketSla['perCs'] as $row)<tr><td>{{ $row['cs_name'] }}</td><td>{{ $row['total'] }}</td><td>{{ number_format($row['avg_hours'], 1) }} jam</td><td>{{ $pct(round(($row['within_sla_count'] / $row['total']) * 100, 2)) }}</td></tr>@empty<tr><td colspan="4" class="empty"><strong>Belum ada tiket ditutup.</strong>Filter periode ini belum memiliki tiket yang selesai dan tercatat CS-nya.</td></tr>@endforelse</tbody></table></div>

            <h3 style="margin:28px 0 4px">Aktivitas Akun Internal</h3>
            <p class="muted" style="margin:0 0 12px">Kapan terakhir tiap akun MA/agen/CS di scope ini login &mdash; diurutkan dari yang paling lama tidak aktif.</p>
            <div class="table-wrap"><table class="table qris-table"><thead><tr><th>Nama</th><th>Role</th><th>Terakhir Login</th></tr></thead><tbody>@forelse($analyticsAccountActivity['rows'] as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['role'] }}</td><td>@if($row['last_login'])<span class="badge {{ $row['days_since_login'] > 14 ? 'danger' : ($row['days_since_login'] > 7 ? 'warn' : 'ok') }}">{{ $row['days_since_login'] }} hari lalu</span>@else<span class="badge danger">Belum pernah login</span>@endif</td></tr>@empty<tr><td colspan="3" class="empty"><strong>Belum ada akun terdeteksi.</strong></td></tr>@endforelse</tbody></table></div>

            <h3 style="margin:28px 0 4px">Analitik Kegagalan Provisioning</h3>
            <p class="muted" style="margin:0 0 12px">Toko yang gagal disetup ke gateway, plus error yang paling sering muncul &mdash; total saat ini: <strong>{{ $analyticsProvisioningFailures['totalFailed'] }} toko</strong>.</p>
            @if(count($analyticsProvisioningFailures['topErrors']) > 0)
            <div class="table-wrap"><table class="table qris-table"><thead><tr><th>Error</th><th>Jumlah Toko</th></tr></thead><tbody>@foreach($analyticsProvisioningFailures['topErrors'] as $err)<tr><td>{{ $err['error'] }}</td><td>{{ $err['count'] }}</td></tr>@endforeach</tbody></table></div>
            @endif
            <div class="table-wrap"><table class="table qris-table"><thead><tr><th>Toko</th><th>Error</th><th>Percobaan</th><th>Terakhir Dicoba</th></tr></thead><tbody>@forelse($analyticsProvisioningFailures['rows'] as $row)<tr><td>{{ $row['merchant_name'] }}</td><td>{{ $row['error'] }}</td><td>{{ $row['attempts'] }}</td><td>{{ $row['last_attempt'] ?? '-' }}</td></tr>@empty<tr><td colspan="4" class="empty"><strong>Tidak ada toko yang gagal provisioning saat ini.</strong> Semua toko di scope ini berhasil disetup ke gateway.</td></tr>@endforelse</tbody></table></div>
