            @php($pct = fn ($value) => number_format((float) $value, 3, ',', '.').'%')
            <div class="grid qris-metrics section">
                <div class="card pad qris-metric primary"><span>Transaksi Dibuat</span><strong>{{ number_format($analyticsPerformance['generated'], 0, ',', '.') }}</strong><small>{{ $periodLabel }}</small></div>
                <div class="card pad qris-metric success"><span>Berhasil Bayar</span><strong>{{ number_format($analyticsPerformance['succeeded'], 0, ',', '.') }}</strong><small>Status sukses</small></div>
                <div class="card pad qris-metric warn"><span>Conversion Rate</span><strong>{{ $pct($analyticsPerformance['conversionRate']) }}</strong><small>Dibuat &rarr; Berhasil</small></div>
            </div>
            <p class="muted" style="margin:0 0 8px">Funnel 2 tahap (data QR di-scan tapi gagal bayar belum tersedia). Heatmap jam &times; hari (WIB), makin gelap makin padat.</p>
            <div class="table-wrap ma-heatmap-wrap"><table class="table qris-table ma-heatmap-table"><thead><tr><th>Hari</th>@for($h = 0; $h < 24; $h++)<th>{{ $h }}</th>@endfor</tr></thead><tbody>@foreach($analyticsPerformance['dayLabels'] as $i => $day)<tr><td><strong>{{ $day }}</strong></td>@foreach($analyticsPerformance['matrix'][$i] as $cnt)@php($intensity = $analyticsPerformance['maxCell'] > 0 ? $cnt / $analyticsPerformance['maxCell'] : 0)<td class="ma-heatmap-cell" style="background:rgba(21,87,194,{{ number_format($intensity, 3) }})" title="{{ $cnt }} transaksi">{{ $cnt > 0 ? $cnt : '' }}</td>@endforeach</tr>@endforeach</tbody></table></div>

            <h3 style="margin:28px 0 4px">Latency Processing</h3>
            <p class="muted" style="margin:0 0 12px">Rata-rata waktu dari transaksi masuk sampai berhasil &mdash; rata-rata keseluruhan: <strong>{{ number_format($analyticsLatency['overallAvgSeconds'], 1) }} detik</strong>. Kalau tiba-tiba melonjak, tanda ada masalah di gateway/bank.</p>
            <div class="table-wrap"><table class="table qris-table ma-paginate"><thead><tr><th>Tanggal</th><th>Rata-rata Latency</th></tr></thead><tbody>@forelse($analyticsLatency['labels'] as $i => $label)<tr><td>{{ $label }}</td><td>{{ number_format($analyticsLatency['avgSeconds'][$i], 1) }} detik</td></tr>@empty<tr><td colspan="2" class="empty"><strong>Belum ada data.</strong>Filter periode ini belum memiliki transaksi sukses dengan waktu selesai tercatat.</td></tr>@endforelse</tbody></table></div>

            <h3 style="margin:28px 0 4px">Breakdown Reliabilitas per Bank/Channel</h3>
            <p class="muted" style="margin:0 0 12px">Persentase sukses per bank/channel pembayaran &mdash; data konkret buat komplain atau negosiasi ke gateway kalau ada bank tertentu yang sering gagal.</p>
            <div class="table-wrap"><table class="table qris-table ma-paginate"><thead><tr><th>Bank/Channel</th><th>Total Transaksi</th><th>Sukses</th><th>% Sukses</th></tr></thead><tbody>@forelse($analyticsChannelReliability['rows'] as $row)<tr><td>{{ $row['channel'] }}</td><td>{{ number_format($row['total'], 0, ',', '.') }}</td><td>{{ number_format($row['successCount'], 0, ',', '.') }}</td><td><span class="badge {{ $row['successRate'] >= 90 ? 'ok' : ($row['successRate'] >= 70 ? 'warn' : 'danger') }}">{{ $pct($row['successRate']) }}</span></td></tr>@empty<tr><td colspan="4" class="empty"><strong>Belum ada data channel.</strong>Filter periode ini belum memiliki transaksi dengan info bank/channel tercatat.</td></tr>@endforelse</tbody></table></div>
